version: "3.9"

services:

  backend:
    container_name: whiteboard_backend
    image: whiteboard:1
    build:
      context: ./backend/whiteboard/
    ports:
      - "8080:8080"
    environment:
       DB_SERVER: ${DB_SERVER}

  postgresql:
    container_name: postgres
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - whiteboard_volume:/var/lib/postgresql/data

  angular-app:
    container_name: whiteboard-app
    build:
      context: ./frontend/whiteboard-app
    image: whiteboard-frontend
    ports:
      - "4200:80"
    volumes:
      - .:/whiteboard-app

volumes:
  whiteboard_volume:
