global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'whiteboard-tool'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    basic_auth:
      username: whiteboard_actuator1
      password: white
    static_configs:
      - targets: ['host.docker.internal:8080']
